services:
  Flask_App:
    restart: unless-stopped
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - mode: ingress
        target: 5000
        published: 5000
    environment:
      - MONGO_URI={Your_URI}
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://127.0.0.1:5000/" ]
