services:
  Flask_App:
    restart: unless-stopped
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - mode: ingress
        target: 5000
        published: 5000
    environment:
      - MONGO_URI=mongodb+srv://tiwarikaushal2012:Ekpassword@cluster0.otvtm.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://127.0.0.1:5000/" ]
